### ISSUE TITLE
Plugin Doesn't work!

### ISSUE THREAD

**Issue by ymomfe** [J-VdS/DiscordPlugin#2]
Server Version: build 103.4
Crash:
```
[02-04-2020 | 14:06:08] [E] Failed to load mod file config/mods/discordplugin.jar. Skipping.
[02-04-2020 | 14:06:08] [E] java.lang.NoClassDefFoundError: io/anuke/mindustry/plugin/Plugin
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at mindustry.mod.Mods.loadMod(Mods.java:645)
        at mindustry.mod.Mods.load(Mods.java:247)
        at mindustry.Vars.init(Vars.java:275)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:58)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:75)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: java.lang.ClassNotFoundException: io.anuke.mindustry.plugin.Plugin
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 17 more
```

**Comment by j-vds** [comment]
bot updated to 104
